//#region Using

//using System;
//using System.Collections.Generic;
//using System.ComponentModel;
//using System.Data;
//using System.Drawing;
//using System.Linq;
//using System.Text;

//using Gizmox.WebGUI.Common;
//using Gizmox.WebGUI.Forms;

//#endregion

//namespace mradmin.Forms
//{
//    public partial class frmRxguidline
//    {
//        public frmRxguidline()
//        {
//            //InitializeComponent();
//        }

//        private void frmRxguidline_Load(object sender, EventArgs e)
//        {
//            txtNotes.Text = "FOR SYRUP AND INJECTIONS : \r\n\r\n"+
//                "1.	Pharmacist or Store Keeper must specify quantity \r\n    "+
//                "   (Volume) in Pack/Bottle in 'Qty In Pack' on Stock \r\n   "+
//                "   Registration Screen. \r\n\r\n"+
//                "2.	Pharmacist or Store Keeper must specify cost per \r\n    "+ 
//                "   pack/bottle. \r\n\r\n"+
//                "3.	Doctors can prescribe in mls or mg and system can \r\n    "+
//                "   calculate number of pack/bottle and cost accordingly. \r\n    "+
//                "   E.G. 5mls x 8 x 7 (5mls, Eight Hrly for Seven Days) \r\n    "+
//                "   will amount to 105mls. If there are 60 mls in a \r\n    "+
//                "   pack/bottle, specified in Stock Registration,  \r\n "+
//                "   system will cost for two packs/bottles.\r\n    " +
//                "\r\n\r\n"+
//                "FOR TABS AND CAPS \r\n"+
//                "\r\n"+
//                "1.	Pharmacist or Store Keeper must include dosage (mg) \r\n    "+
//                "   as part of the Description of the Drug - EG. Amoxil Caps \r\n    "+
//                "   500mg. 'Qty in Pack' on Stock Registration Screen must \r\n    "+
//                "   be specified as '0' \r\n    "+
//                "\r\n\r\n"+
//                "2.	Pharmacist must specify cost per tab or cap in \r\n    "+
//                "   stock control system. The practice of costing drugs \r\n    "+
//                "   in pack of 10 or 20 should be avoided.\r\n    "+
//                "\r\n\r\n"+
//                "3. Doctors can prescribe in tabs or caps and system can \r\n    "+
//                "   calculate and cost per number of tabs or caps - \r\n    "+
//                "   EG. 1cap x 6 x 5 (One Cap, Six Hrly for Five Days) \r\n    "+
//                "   will amount to 20 caps and system will cost according \r\n    "+
//                "\r\n\r\n"+
//                "Note for Doctors : \r\n"+
//                "\r\n"+
//                "Multiple Asterix ('******') on Qty Required is an indication \r\n " +
//                "of invalid 'Qty In pack' specification in Stock Control Sys\r\n   " +
//                "The Cost that will be generated by system will be outragious.\r\n " +
//                "Doctors are therefore advised to indicate on 'Qty Reqd' Col, \r\n" +
//                "actual qty to deduct from stock in order for the system \r\n" +
//                "TO generate acurate cost TO the patient.";
//        }

//        //private void btnClose_Click(object sender, EventArgs e)
//        //{
//        //    this.Close();
//        //}
//    }
//}